"use client";

import { motion, useReducedMotion, type Variants } from "motion/react";
import { duration, ease, stagger } from "@/lib/motion-config";

const container: Variants = {
  hidden: {},
  show: {
    transition: { staggerChildren: stagger.word, delayChildren: 0.6 },
  },
};

// Each word lands with a tiny rotation and lift, like a fountain pen pressing
// onto warm paper. The aggregate effect reads as handwriting, but the type
// system stays inside Fraunces — no second display face needed.
const word: Variants = {
  hidden: { opacity: 0, y: "0.32em", rotate: -1.8, filter: "blur(5px)" },
  show: {
    opacity: 1,
    y: 0,
    rotate: 0,
    filter: "blur(0)",
    transition: { duration: duration.slow, ease: ease.out },
  },
};

// IntentionReveal renders the day's intention in a near-handwriting register.
// Fraunces italic with low SOFT axis, slightly looser letterspacing, slow
// per-word stagger with a small rotation. Reads like it was just written
// by someone who has met the resident, not generated by a system.
export function IntentionReveal({ text }: { text: string }) {
  const reduced = useReducedMotion();
  const baseClass =
    "font-serif italic text-[1.15rem] sm:text-[1.45rem] lg:text-[1.7rem] text-[var(--color-ink)] max-w-[34ch] mt-6 leading-[1.2]";
  const baseStyle = {
    fontVariationSettings: '"opsz" 24, "SOFT" 100',
    letterSpacing: "0.005em",
  } as const;

  if (reduced) {
    return (
      <p className={baseClass} style={baseStyle}>
        {text}
      </p>
    );
  }
  const words = text.split(/(\s+)/);
  return (
    <motion.p
      className={baseClass}
      style={baseStyle}
      variants={container}
      initial="hidden"
      animate="show"
    >
      {words.map((w, i) =>
        /^\s+$/.test(w) ? (
          <span key={`s-${i}`}>{w}</span>
        ) : (
          <motion.span
            key={`w-${i}`}
            variants={word}
            className="inline-block"
            style={{ willChange: "transform, opacity, filter" }}
          >
            {w}
          </motion.span>
        )
      )}
    </motion.p>
  );
}
